### ISSUE TITLE
手册高级类型->映射类型中有一处注解错误

### ISSUE THREAD

**Issue by fatcatmimi** [bosens-China/Typescript-manual#11]
你好:
  type Bar<T> = T extends { a: (x: infer U) => void; b: (x: infer U) => void }
    ? U
    : never;
  type T20 = Bar<{ a: (x: string) => void; b: (x: string) => void }>; // string
  type T21 = Bar<{ a: (x: string) => void; b: (x: number) => void }>; // string & number      ### 这个地方错误  T21的类型应该为nerver

**Comment by bosens-China** [comment]
多谢反馈，这里信息来源于 https://github.com/zhongsp/TypeScript 请移步反馈
