### ISSUE TITLE
命名空间 & 命名空间和模块 页面重复

### ISSUE THREAD

**Issue by casey0808** [bosens-China/Typescript-manual#8]
<img width="317" alt="Screen Shot 2021-02-03 at 17 29 16" src="https://user-images.githubusercontent.com/14999541/106726543-75cbd000-6645-11eb-9571-f3efba80d1d5.png">

改了名字但没有删除之前的页面？

**Comment by bosens-China** [comment]
是对方的数据来源重复了，这个问题可以在[https://github.com/zhongsp/TypeScript/issues](https://github.com/zhongsp/TypeScript/issues)反馈

[https://github.com/zhongsp/TypeScript/blob/dev/handbook/namespaces.md](https://github.com/zhongsp/TypeScript/blob/dev/handbook/namespaces.md)
[https://github.com/zhongsp/TypeScript/blob/dev/handbook/namespaces-and-modules.md](https://github.com/zhongsp/TypeScript/blob/dev/handbook/namespaces-and-modules.md)

**Comment by casey0808** [comment]
数据源里两个页面是不一样的诶

**Comment by bosens-China** [comment]
收到，明天解决一下

**Comment by bosens-China** [comment]
已修复，还有什么其他建议欢迎提出
